In [2]:
import numpy as np

In [2]:
np.sqrt(10)

3.1622776601683795

In [3]:
print('minimum ',np.amin([25,30,57,18]))

minimum  18


In [4]:
print('maximum ',np.amax([25,30,57,18]))

maximum  57


In [5]:
np.ceil(29.5)

30.0

In [6]:
np.ceil(np.sqrt(10))

4.0

In [7]:
np.ceil(np.sum(np.sqrt([5,10,15])))

10.0

In [8]:
np.array([5,9,13])

array([ 5,  9, 13])

In [9]:
type([5,9,13])

list

In [14]:
a = np.array([[1,2],[3,4],[4,5]])

print('Type-   ', a.dtype)

print('\n ', '-' * 30)

print('\n ',a)

Type-    int32

  ------------------------------

  [[1 2]
 [3 4]
 [4 5]]


In [15]:
np.array([1,2,3], dtype= float)

array([1., 2., 3.])

In [16]:
a= np.array(np.mat('1,2,3;3,4,5'))

array([[1, 2, 3],
       [3, 4, 5]])

In [17]:
a= [1,2]

c = np.array(a)

print(c)


[1 2]


In [18]:
b = np.asarray(c)

print(b)

[1 2]


In [21]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)

print('Type/class of Matrix',type(mat))
print('Here is the matrix \n--------\n ',mat,'\n ----------')
print('Dimension of the matrix: ',mat.ndim,sep ='')
print('size of the matrix: ',mat.size,sep= '')
print('shape of the matrix: ',mat.shape)
print('Data type of matrix: ',mat.dtype)



Type/class of Matrix <class 'numpy.ndarray'>
Here is the matrix 
--------
  [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 ----------
Dimension of the matrix: 2
size of the matrix: 9
shape of the matrix:  (3, 3)
Data type of matrix:  int32


In [22]:
a = np.arange(2,10.5,.4)
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [23]:
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [24]:
print('every 5th number from 50 in reverse order \n',np.arange(50,0,-5))

every 5th number from 50 in reverse order 
 [50 45 40 35 30 25 20 15 10  5]


In [25]:
print('Five elements linearly spaced between 10 & 40 \n ---------------')
print(np.linspace(10,40,5))

Five elements linearly spaced between 10 & 40 
 ---------------
[10.  17.5 25.  32.5 40. ]


In [26]:
np.linspace(2.0,3.0,4,endpoint= False,retstep =True)

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)

In [27]:
print(np.linspace(4.567,26.876,34,retstep = True))

(array([ 4.567     ,  5.2430303 ,  5.91906061,  6.59509091,  7.27112121,
        7.94715152,  8.62318182,  9.29921212,  9.97524242, 10.65127273,
       11.32730303, 12.00333333, 12.67936364, 13.35539394, 14.03142424,
       14.70745455, 15.38348485, 16.05951515, 16.73554545, 17.41157576,
       18.08760606, 18.76363636, 19.43966667, 20.11569697, 20.79172727,
       21.46775758, 22.14378788, 22.81981818, 23.49584848, 24.17187879,
       24.84790909, 25.52393939, 26.1999697 , 26.876     ]), 0.6760303030303031)


In [4]:
print('vector of zeros \n ------------')
print(np.zeros(5))

vector of zeros 
 ------------
[0. 0. 0. 0. 0.]


In [5]:
print('vector of ones \n -------------')
print(np.ones(7))

vector of ones 
 -------------
[1. 1. 1. 1. 1. 1. 1.]


In [9]:
print("Matrix of 5's \n ------------------")
      
      
print(5 *np.ones(7))      

Matrix of 5's 
 ------------------
[5. 5. 5. 5. 5. 5. 5.]


In [11]:
print("Matrix of ones \n ------------")
print(np.ones((3,5)))

Matrix of ones 
 ------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
print("Matrix of 5's \n ----------------")
print(np.ones((4,5)))

Matrix of 5's 
 ----------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
y = np.arange(30).reshape(5,6)
print(y)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [18]:
np.random.seed(6)
print('random number generation fixed pattern \n ----')

print(np.random.rand(10,6))

random number generation fixed pattern 
 ----
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [23]:
np.random.seed(50)
print('random number generation fixed pattern \n ----')

print(np.random.rand(10,6))

random number generation fixed pattern 
 ----
[[0.49460165 0.2280831  0.25547392 0.39632991 0.3773151  0.99657423]
 [0.4081972  0.77189399 0.76053669 0.31000935 0.3465412  0.35176482]
 [0.14546686 0.97266468 0.90917844 0.5599571  0.31359075 0.88820004]
 [0.67457307 0.39108745 0.50718412 0.5241035  0.92800093 0.57137307]
 [0.66833757 0.05225869 0.3270573  0.05640164 0.17982769 0.92593317]
 [0.93801522 0.71409271 0.73268761 0.46174768 0.93132927 0.40642024]
 [0.68320577 0.64991587 0.59876518 0.22203939 0.68235717 0.8780563 ]
 [0.79671726 0.43200225 0.91787822 0.78183368 0.72575028 0.12485469]
 [0.91630845 0.38771099 0.29492955 0.61673141 0.46784623 0.25533891]
 [0.83899589 0.1786192  0.22711417 0.65987645 0.47911625 0.07344734]]


In [25]:
print('Numbers from normal distribution with zero mean & s.d 1 \n -----------')
print(np.random.randn(10,3))

Numbers from normal distribution with zero mean & s.d 1 
 -----------
[[ 2.70525499 -1.49138851  0.09597793]
 [ 0.52468671  0.8156655   0.0515058 ]
 [-0.16455536  0.27819942  0.0871147 ]
 [ 0.03426837  0.74656892 -0.94363758]
 [-0.24577667  1.10812096  0.03900789]
 [-0.21326669 -0.89095461 -0.27064634]
 [ 0.22224372  0.2518136   0.70792609]
 [ 0.49398983  1.47100167 -0.58261947]
 [ 2.06581949  1.08783389  0.80518904]
 [-1.58788484  1.2308855  -2.37345338]]


In [27]:
print('Numbers from normal distribution with zero mean & s.d 1 \n -----------')
c = np.random.randn(2,3)
print(c)

Numbers from normal distribution with zero mean & s.d 1 
 -----------
[[-0.36293111 -2.57091976  0.13751474]
 [-0.71929619  0.72852289  1.62174549]]


In [28]:
np.mean(c)

-0.19422732394170364

In [29]:
print("Random integer vector \n -------")
print(np.random.randint(5,20,10))

Random integer vector 
 -------
[11  9 16  8  5  6 19  8 17 16]


In [30]:
print("Random integer vector \n -------")
print(np.random.randint(5,20,(5,8)))

Random integer vector 
 -------
[[ 9 14 16 17 13  9 10 11]
 [12 10  6 18 10 17 13  8]
 [10 14 19 18  8 15 11 16]
 [19 17 15 15 19  5 18 18]
 [ 5 13 18  5 15 19 17  9]]


In [33]:
print("Random integer vector \n -------")
print(np.random.randint(5,20,(5,2)))

Random integer vector 
 -------
[[13 15]
 [15  5]
 [12 17]
 [10  9]
 [ 9 14]]


In [34]:
emp_salary = np.random.randint(8,70,10)
emp_salary

array([19, 69, 63, 34, 63, 53, 40, 48, 67, 31])

In [37]:
np.clip(emp_salary,a_min= 20,a_max= 50)

array([20, 50, 50, 34, 50, 50, 40, 48, 50, 31])

In [39]:
print(np.where(emp_salary < 40))

(array([0, 3, 9], dtype=int64),)


In [41]:
emp_salary[[1,3,5]]

array([69, 34, 53])

In [52]:
import numpy as np
from numpy.random import randint as ri

a = ri(1,99,30)
a

array([93, 20, 84, 37,  6,  1, 40, 40, 57, 28, 50, 25, 67, 11, 10,  7, 59,
       53, 19, 52, 38, 11, 38, 16, 14, 86,  8, 65, 44, 49])

In [44]:
b = a.reshape(2,3,5)
b

array([[[33, 69, 51, 60, 42],
        [64, 80, 83, 32, 23],
        [67,  6, 66, 34, 90]],

       [[11, 83, 55, 73, 15],
        [82, 58, 80, 93, 34],
        [88, 42, 87, 57, 85]]])

In [46]:
c = a.reshape(6,5)
c

array([[33, 69, 51, 60, 42],
       [64, 80, 83, 32, 23],
       [67,  6, 66, 34, 90],
       [11, 83, 55, 73, 15],
       [82, 58, 80, 93, 34],
       [88, 42, 87, 57, 85]])

In [48]:
print('Max of a = ',c.max())
print('Min of b = ',c.min())

Max of a =  93
Min of b =  6


In [54]:
M = ri(1,100,25).reshape(5,5)
print("Here is matrix \n ",'-'*30,"\n", M)
print("Sorted matrix along row \n ",'-'*30,"\n",np.sort(M))
print("Sorted matrix along cloumn \n",'-'*30,"\n",np.sort(M,axis=0))

Here is matrix 
  ------------------------------ 
 [[11 79 57 72 52]
 [91 26 75 55 46]
 [16  1 94 46  1]
 [58 84 33 37 94]
 [34  5 27 15  5]]
Sorted matrix along row 
  ------------------------------ 
 [[11 52 57 72 79]
 [26 46 55 75 91]
 [ 1  1 16 46 94]
 [33 37 58 84 94]
 [ 5  5 15 27 34]]
Sorted matrix along cloumn 
 ------------------------------ 
 [[11  1 27 15  1]
 [16  5 33 37  5]
 [34 26 57 46 46]
 [58 79 75 55 52]
 [91 84 94 72 94]]


In [55]:
arr = np.arange(13,30)
print("Array",arr)

Array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [56]:
print('element at 7th index is: ',arr[7])

element at 7th index is:  20


In [57]:
print('element from 3rd to 5th',arr[3:6])

element from 3rd to 5th [16 17 18]


In [59]:
print('element last backward are',arr[-1::-2])

element last backward are [29 27 25 23 21 19 17 15 13]


In [60]:
arr =np.arange(0,21,2)
print('new arr',arr)

new arr [ 0  2  4  6  8 10 12 14 16 18 20]


In [61]:
print('element at 2nd,4th,9th index are: ',arr[[2,4,9]])

element at 2nd,4th,9th index are:  [ 4  8 18]


In [65]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
print('élement in row 1 and column 2: ',mat[1][2])

élement in row 1 and column 2:  6


In [69]:
print('element in row 2 :',mat[2])

element in row 2 : [7 8 9]


In [74]:
print('element in row 2 :',mat[2])
print('cloum at index zero & 1\n',mat[:,1:])

element in row 2 : [7 8 9]
cloum at index zero & 1
 [[2 3]
 [5 6]
 [8 9]]


In [75]:
print('x \n',mat[1:2,1:2])

x 
 [[5]]


In [76]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
print('y',mat[0:2,[1,2]])

y [[2 3]
 [5 6]]


In [79]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
mat[0,1] = 35
mat

array([[ 1, 35,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [82]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print('Matrix having 3 row & 5 column :\n',mat)

Matrix having 3 row & 5 column :
 [[51 63 23 34 60]
 [60 37 79 69 83]
 [94 81 71 18 91]]


In [83]:
xyz = mat[mat>70]
xyz

array([79, 83, 94, 81, 71, 91])

In [84]:
print(np.where(mat==63))

(array([0], dtype=int64), array([1], dtype=int64))


In [85]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print('Matrix 1 \n',mat1)
print('Matrix 2 \n',mat2)

Matrix 1 
 [[5 3 3]
 [6 1 8]
 [6 4 1]]
Matrix 2 
 [[2 8 9]
 [4 4 4]
 [1 3 8]]


In [86]:
print('Addition \n',mat1+mat2)

Addition 
 [[ 7 11 12]
 [10  5 12]
 [ 7  7  9]]


In [87]:
start = np.zeros((3,3))
print(start)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [89]:
rows = np.array([[1,0,2]])
print(rows)

[[1 0 2]]


In [90]:
y = start + rows
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [91]:
new_row = rows.T
new_row

array([[1],
       [0],
       [2]])

In [92]:
test = new_row + start
test

array([[1., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.]])

In [93]:
mat1

array([[5, 3, 3],
       [6, 1, 8],
       [6, 4, 1]])

In [94]:
print('square root of mat1: \n',np.sqrt(mat1))

square root of mat1: 
 [[2.23606798 1.73205081 1.73205081]
 [2.44948974 1.         2.82842712]
 [2.44948974 2.         1.        ]]
